baseURL: "https://buscandoaverroes.github.io/"
theme: blowfish
defaultContentLanguage: en
enableRobotsTXT: yes
paginate: 10
summaryLength: 0
buildDrafts: no
buildFuture: no
imaging:
  anchor: Center
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5
outputs:
  home:
    - HTML
    - RSS
    - JSON
privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: false
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: false

